header:
  version: 8

machine: raspberrypi4-64
distro: poky
target:
  - core-image-base

repos:
  meta-my-raspberrypi:
    layers:
      meta-my-security:

  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/poky
    branch: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded.git
    path: layers/meta-openembedded
    branch: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    path: layers/meta-raspberrypi
    branch: kirkstone

  meta-qt5:
    url: https://github.com/meta-qt5/meta-qt5/
    path: layers/meta-qt5
    branch: kirkstone
  
  meta-security:
    url: https://git.yoctoproject.org/meta-security
    path: layers/meta-security
    branch: kirkstone
  
  meta-rauc:
    url: https://github.com/rauc/meta-rauc
    path: layers/meta-rauc
    branch: kirkstone

local_conf_header:
  standard:
    PACKAGE_CLASSES = "package_deb"
  raspi-u-boot: |
    ENABLE_UART = "1"
    RPI_USE_U_BOOT = "1"
    PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
  my-fitimage:  |
    KERNEL_CLASSES = "kernel-fitimage"
    KERNEL_IMAGETYPE = "fitImage"
    KERNEL_BOOTCMD = "bootm 0x4000000"
  my-dmverity:  |
    DISTRO_FEATURES:append = " security"
    DISTRO_FEATURES:append = " integrity"
    DM_VERITY_IMAGE = "core-image-base"
    DM_VERITY_IMAGE_TYPE = "ext4"
    IMAGE_CLASSES += "dm-verity-img"
    INITRAMFS_IMAGE = "my-initramfs"
    IMAGE_BOOT_FILES:append = " fitImage-my-initramfs-raspberrypi4-64-raspberrypi4-64"
    WKS_FILE = "my-security.wks.in"
