header:
  version: 8

machine: raspberrypi4-64
distro: poky
target:
  - core-image-minimal

repos:
  meta-my-raspberrypi:
    layers:
      meta-my-security:

  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/poky
    refspec: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    refspec: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    path: layers/meta-raspberrypi
    refspec: kirkstone

  meta-qt5:
    url: https://github.com/meta-qt5/meta-qt5/
    path: layers/meta-qt5
    refspec: kirkstone

local_conf_header:
  standard:
    PACKAGE_CLASSES = "package_deb"
