
name: Run on Push to  Branch

on:
  push:
    branches:
      - check_vulnerability

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update && \
            sudo apt upgrade -y && \
            sudo apt install -y \
            build-essential \
            chrpath \
            cpio \
            debianutils \
            diffstat \
            file \
            gawk \
            gcc \
            git \
            iputils-ping \
            libacl1 \
            liblz4-tool \
            locales \
            python3 \
            python3-git \
            python3-jinja2 \
            python3-pexpect \
            python3-pip \
            python3-subunit \
            socat \
            texinfo \
            unzip \
            wget \
            xz-utils \
            zstd \
            sudo \
            locales && \
            apt clean

          # gen locale
          sudo locale-gen en_US.UTF-8 && \
            sudo update-locale LANG=en_US.UTF-8

      - name: Fetch dependency
        run: |
          kas checkout kas-my-security.yml

      - name: Add cve-check
        run: |
          echo "INHERIT += \"cve-check\"" >> build/conf/local.conf

      - name: Restore yocto download cache
        uses: actions/cache@v4
        with:
          path: build/download
          key: yocto_dl

      - name: Restore yocto sstate cache
        uses: actions/cache@v4
        with:
          path: build/sstate-cache
          key: yocto_sstate

      - name: Run cve-check
        run: |
          . layers/poky/oe-init-build-env build/
          bitbake core-image-base

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: cve-result
          path: build/tmp/deploy/cve

      - name: Check CVE
        if: false
        run: |
          