
name: Run on Push to  Branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, yocto-build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch dependency
        run: |
          kas checkout kas-my-security.yml

      - name: Add cve-check
        run: |
          echo "INHERIT += \"cve-check\""   >> build/conf/local.conf
          echo "BB_NUMBER_THREADS = '6'"  >> build/conf/local.conf
          echo "PARALLEL_MAKE = '-j 4'"   >> build/conf/local.conf

      - name: Compress downloads
        run: |
          mkdir -p cache-compressed
          if [ -d build/downloads ]; then
            tar -I 'zstd -19' -cf cache-compressed/downloads.tar.zst -C build downloads
          fi
  
      - name: Restore downloads from cache
        uses: actions/cache@v4
        with:
          path: cache-compressed/downloads.tar.zst
          key: yocto_downloads-${{ runner.os }}-${{ hashFiles('build/conf/local.conf') }}
          restore-keys: |
            yocto_downloads-${{ runner.os }}-
            yocto_downloads-

      - name: Compress sstate-cache
        run: |
          mkdir -p cache-compressed
          if [ -d build/sstate-cache ]; then
            tar -I 'zstd -19' -cf cache-compressed/sstate-cache.tar.zst -C build sstate-cache
          fi

      - name: Restore sstate-cache from cache
        uses: actions/cache@v4
        with:
          path: cache-compressed/sstate-cache.tar.zst
          key: yocto_sstate_compressed-${{ runner.os }}-${{ hashFiles('build/conf/local.conf') }}
          restore-keys: |
            yocto_sstate_compressed-${{ runner.os }}-
            yocto_sstate_compressed-

      - name: Extract sstate-cache
        run: |
          if [ -f cache-compressed/sstate-cache.tar.zst ]; then
            mkdir -p build
            tar -I 'zstd -d' -xf cache-compressed/sstate-cache.tar.zst -C build
          fi

      - name: Run cve-check
        run: |
          . layers/poky/oe-init-build-env build/
          bitbake core-image-base

      - name: Re-compress sstate-cache after build
        run: |
          rm -f cache-compressed/sstate-cache.tar.zst
          tar -I 'zstd -19' -cf cache-compressed/sstate-cache.tar.zst -C build sstate-cache

      - name: Re-compress downloads after build
        run: |
          rm -f cache-compressed/downloads.tar.zst
          tar -I 'zstd -19' -cf cache-compressed/downloads.tar.zst -C build downloads

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: cve-result
          path: build/tmp/deploy/cve

      - name: Check CVE
        if: false
        run: |
          